version: "3"
services:
  app:
    build: ./app
    restart: on-failure
    depends_on:
      - db
      - elasticsearch
      #- kibana
    ports:
      - "5001:5000"

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: mysql search -h 127.0.0.1 -u root --password=root

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9200"

  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt/
#  kibana:
#      image: docker.elastic.co/kibana/kibana:7.0.0
#      ports:
#        - "5601:5601"
#      logging:
#        driver: none
