version: "3"
services:
  app:
    build: ./app
    restart: on-failure
    depends_on:
      - db
      - elasticsearch
      #- kibana
    ports:
      - "80:80"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    logging:
      driver: none

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    logging:
      driver: none

  kibana:
      image: docker.elastic.co/kibana/kibana:7.0.0
      ports:
        - "5601:5601"
      logging:
        driver: none
