CREATE DATABASE search;
use search;

CREATE TABLE bbc(id INT(6) UNSIGNED PRIMARY KEY, content TEXT NOT NULL, tags TEXT NOT NULL);
ALTER TABLE bbc MODIFY tags TEXT CHARACTER SET utf8;

CREATE TABLE s3_connections(id INT(6) UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(50) NOT NULL UNIQUE, access_key_id TEXT NOT NULL, access_key TEXT NOT NULL, bucket TEXT NOT NULL, region TEXT NOT NULL, PRIMARY KEY(id));